name: Docker PostGIS CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        postgres: [9.6, 10, 11, 12, 13, '14rc1']
        postgis: ['2.5', '3.1']
        variant: [default, alpine]
        exclude:
          - postgres: 12
            postgis: '2.5'
          - postgres: 13
            postgis: '2.5'
          - postgres: '14rc1'
            postgis: '2.5'
          - postgres: 9.6
            postgis: '2.5'
            variant: default
          - postgres: 10
            postgis: '2.5'
            variant: default
          - postgres: 11
            postgis: '2.5'
            variant: default
        include:
          - postgres: 13
            postgis: master
            variant: default
          - postgres: 14rc1
            postgis: master
            variant: default
    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build docker image for ${{ env.VERSION }} ${{ env.VARIANT }}
      run: make test

    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push docker image to dockerhub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: make push

